name = "GModelFitViewer"
uuid = "5d93b50e-5cc7-4feb-a740-ec85257caa01"
version = "0.5.1"
authors = ["Luciano Nicastro <luciano.nicastro@gmail.com>"]

[deps]
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
GModelFit = "ac42e6ba-c0bf-4fcf-827d-deea44b16255"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructC14N = "d2514e9c-36c4-5b8e-97e2-51e7675c221c"
TypedJSON = "82102e82-2b72-4f25-ab3c-19001ac49e20"

[compat]
Dates = "1.11.0"
DefaultApplication = "^1.1"
GModelFit = "^0.8"
JSON = "^1.1"
StructC14N = "^0.3"
Test = "1.11.0"
TypedJSON = "0.1.2"
julia = "1.11"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[targets]
test = ["Test", "Dates", "Interpolations"]
